version: '3'

services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    # ports:
    #   - 6379:6379
    networks:
      - appnet
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:11
    restart: always
    networks:
      - appnet
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - 5000:5000
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - appnet

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  appnet:
    driver: bridge
