version: '3'
services:
	redis:
		image: ./df-redis
		command: ["redis-server", "--appendonly", "yes"]
		restart: always
		ports:
			- "6379:6379"
		volumes:
			- redis-data:/data

	postgres:
		image: ./df-postgres
		restart: always
		volumes:
			- postgres-data:/var/lib/postgresql/data

	api:
		image: ./df-api
		restart: always
		ports:
			- "5001:5001"
		links:
			- postgres
			- redis
		depends_on:
			- postgres
			- redis
	
	nginx:
		image: ./df-nginx
		restart: always
		ports:
			- "8080:8080"

	# ui:
	# 	image: .
	# 	links:
	# 		- api
	# 	ports:
	# 		- 5000:5000

	volumes:
		postgres-data:
		redis-data: